version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=cypress
      - POSTGRES_USER=cypress
      - POSTGRES_DB=cypressworkshop
